DELETE http://localhost:3003/api/blogs/68421070fa6cf3a3f5cea905
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI2ODNlNGMwYWYwNzExYTM5ZDNkZjYyOTMiLCJpYXQiOjE3NDkwOTA4ODh9.P4OqTdb1o3J0vvhLNN6E5bw8rFzHuHCjDe2JBtxuosM